"""initial_schema

Revision ID: 7da8909de0f3
Revises: 
Create Date: 2026-08-03 10:41:21.192309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7da8909de0f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.String(), nullable=False),
    sa.Column('rolling_avg_accuracy', sa.Float(), nullable=False),
    sa.Column('rolling_avg_relevance', sa.Float(), nullable=False),
    sa.Column('rolling_avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=False),
    sa.Column('drift_type', sa.String(), nullable=False),
    sa.Column('window_run_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_snapshots_feature_id'), 'drift_snapshots', ['feature_id'], unique=False)
    op.create_table('prompt_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('yaml_content', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_configs_feature_id'), 'prompt_configs', ['feature_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_config_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_accuracy', sa.Float(), nullable=True),
    sa.Column('avg_relevance_score', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('passed_cases', sa.Integer(), nullable=True),
    sa.Column('failed_cases', sa.Integer(), nullable=True),
    sa.Column('regressions', sa.Integer(), nullable=True),
    sa.Column('improvements', sa.Integer(), nullable=True),
    sa.Column('comparison_baseline_id', sa.UUID(), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('report_url', sa.String(), nullable=True),
    sa.Column('git_sha', sa.String(), nullable=True),
    sa.Column('pr_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_baseline_id'], ['eval_runs.id'], ),
    sa.ForeignKeyConstraint(['prompt_config_id'], ['prompt_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_prompt_config_id'), 'eval_runs', ['prompt_config_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eval_run_id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.String(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_match', sa.Boolean(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('judge_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_eval_run_id'), 'eval_results', ['eval_run_id'], unique=False)
    op.create_index(op.f('ix_eval_results_test_case_id'), 'eval_results', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_results_test_case_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_eval_run_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_eval_runs_prompt_config_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_prompt_configs_feature_id'), table_name='prompt_configs')
    op.drop_table('prompt_configs')
    op.drop_index(op.f('ix_drift_snapshots_feature_id'), table_name='drift_snapshots')
    op.drop_table('drift_snapshots')
    # ### end Alembic commands ###
