"""add organization_id for multi-tenancy

Revision ID: 9b139aa6cc9b
Revises: 7da8909de0f3
Create Date: 2026-08-03 12:29:38.065837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b139aa6cc9b'
down_revision: Union[str, None] = '7da8909de0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_snapshots', sa.Column('organization_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_drift_snapshots_organization_id'), 'drift_snapshots', ['organization_id'], unique=False)
    op.add_column('eval_runs', sa.Column('organization_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_eval_runs_organization_id'), 'eval_runs', ['organization_id'], unique=False)
    op.add_column('prompt_configs', sa.Column('organization_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_prompt_configs_organization_id'), 'prompt_configs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_configs_organization_id'), table_name='prompt_configs')
    op.drop_column('prompt_configs', 'organization_id')
    op.drop_index(op.f('ix_eval_runs_organization_id'), table_name='eval_runs')
    op.drop_column('eval_runs', 'organization_id')
    op.drop_index(op.f('ix_drift_snapshots_organization_id'), table_name='drift_snapshots')
    op.drop_column('drift_snapshots', 'organization_id')
    # ### end Alembic commands ###
