"""add production log model

Revision ID: b7c8d9e0f1a2
Revises: 6f1d2a3b4c5d
Create Date: 2026-08-28 05:37:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7c8d9e0f1a2'
down_revision = '6f1d2a3b4c5d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('feature_id', sa.String(), nullable=False),
    sa.Column('prompt_config_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('user_feedback_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_config_id'], ['prompt_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_logs_created_at'), 'production_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_production_logs_feature_id'), 'production_logs', ['feature_id'], unique=False)
    op.create_index(op.f('ix_production_logs_organization_id'), 'production_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_logs_organization_id'), table_name='production_logs')
    op.drop_index(op.f('ix_production_logs_feature_id'), table_name='production_logs')
    op.drop_index(op.f('ix_production_logs_created_at'), table_name='production_logs')
    op.drop_table('production_logs')
    # ### end Alembic commands ###
