"""add routing decision model

Revision ID: c8d9e0f1a2b3
Revises: b7c8d9e0f1a2
Create Date: 2026-08-28 05:42:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8d9e0f1a2b3'
down_revision = 'b7c8d9e0f1a2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_decisions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('feature_id', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=False),
    sa.Column('routed_model', sa.String(), nullable=False),
    sa.Column('cost_saved_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_decisions_created_at'), 'routing_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_routing_decisions_feature_id'), 'routing_decisions', ['feature_id'], unique=False)
    op.create_index(op.f('ix_routing_decisions_input_hash'), 'routing_decisions', ['input_hash'], unique=False)
    op.create_index(op.f('ix_routing_decisions_organization_id'), 'routing_decisions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routing_decisions_organization_id'), table_name='routing_decisions')
    op.drop_index(op.f('ix_routing_decisions_input_hash'), table_name='routing_decisions')
    op.drop_index(op.f('ix_routing_decisions_feature_id'), table_name='routing_decisions')
    op.drop_index(op.f('ix_routing_decisions_created_at'), table_name='routing_decisions')
    op.drop_table('routing_decisions')
    # ### end Alembic commands ###
