"""add is_superadmin and otp table

Revision ID: ee5a55b2d0bc
Revises: e49a26840257
Create Date: 2026-08-03 12:53:28.117350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5a55b2d0bc'
down_revision: Union[str, None] = 'e49a26840257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_passwords',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_time_passwords_email'), 'one_time_passwords', ['email'], unique=False)
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    op.drop_index(op.f('ix_one_time_passwords_email'), table_name='one_time_passwords')
    op.drop_table('one_time_passwords')
    # ### end Alembic commands ###
