"""add semantic cache model

Revision ID: f1a2b3c4d5e6
Revises: e0f1a2b3c4d5
Create Date: 2026-08-28 06:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'e0f1a2b3c4d5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semantic_cache',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('feature_id', sa.String(), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('cached_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_cache_feature_id'), 'semantic_cache', ['feature_id'], unique=False)
    op.create_index(op.f('ix_semantic_cache_organization_id'), 'semantic_cache', ['organization_id'], unique=False)
    op.create_index(op.f('ix_semantic_cache_prompt_hash'), 'semantic_cache', ['prompt_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_cache_prompt_hash'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_organization_id'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_feature_id'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    # ### end Alembic commands ###
